create or replace function public.get_current_cash_summary()
returns table (cash_day_id uuid, operational_date date, opening_balance numeric(14, 2), opening_updated_at timestamptz, current_balance text, movements jsonb, categories jsonb, closed_at timestamptz, closed_by uuid, closed_by_display_name text, closure_kind text, closing_balance numeric(14, 2))
language plpgsql security definer set search_path = '' as $$
declare day public.cash_days%rowtype; v_date date;
begin
  if not public.cash_current_actor_is_operational() then raise exception 'No tenés permiso para consultar la caja.'; end if;
  v_date := (now() at time zone 'America/Argentina/Cordoba')::date; perform public.ensure_current_cash_day(); select * into day from public.cash_days candidate where candidate.operational_date = v_date for update;
  return query select day.id, day.operational_date, day.opening_balance, day.opening_updated_at, (day.opening_balance + coalesce((select sum(case when not item.voided then case when item.direction = 'income' then item.amount else -item.amount end else 0 end) from public.cash_m10_effective_movements(day.id) item), 0::numeric))::text,
    coalesce((select jsonb_agg(jsonb_build_object('id', item.movement_id, 'direction', item.direction, 'amount', item.amount, 'description', item.description, 'expense_category_id', item.expense_category_id, 'expense_category_code', item.expense_category_code, 'expense_category_name', item.expense_category_name, 'actor_id', item.actor_id, 'actor_display_name', coalesce((select profile.display_name from public.profiles profile where profile.id = item.actor_id), 'Sistema'), 'created_at', item.created_at) order by item.created_at desc, item.movement_id desc) from public.cash_m10_effective_movements(day.id) item where not item.voided), '[]'::jsonb), coalesce((select jsonb_agg(jsonb_build_object('id', category.id, 'code', category.code, 'name', category.name) order by category.code) from public.cash_expense_categories category where category.is_active), '[]'::jsonb), day.closed_at, day.closed_by, (select profile.display_name from public.profiles profile where profile.id = day.closed_by), day.closure_kind, day.closing_balance;
end; $$;

create or replace function public.get_cash_day_summary(p_cash_day_id uuid)
returns table (cash_day_id uuid, operational_date date, opening_balance numeric(14, 2), opening_updated_at timestamptz, closed_at timestamptz, closed_by uuid, closed_by_display_name text, closure_kind text, closing_balance text, movements jsonb, events jsonb, lifecycle_events jsonb)
language plpgsql security definer set search_path = '' as $$ declare day public.cash_days%rowtype;
begin
  if not public.cash_current_actor_is_operational() then raise exception 'No tenés permiso para consultar la caja.'; end if; select * into day from public.cash_days where id = p_cash_day_id; if not found then raise exception 'La caja no existe.'; end if; if day.closed_at is null then raise exception 'La caja seleccionada todavía está abierta.'; end if;
  return query select day.id, day.operational_date, day.opening_balance, day.opening_updated_at, day.closed_at, day.closed_by, (select profile.display_name from public.profiles profile where profile.id = day.closed_by), day.closure_kind, day.closing_balance::text,
    coalesce((select jsonb_agg(jsonb_build_object('id', item.movement_id, 'direction', item.direction, 'amount', item.amount, 'description', item.description, 'expense_category_id', item.expense_category_id, 'expense_category_code', item.expense_category_code, 'expense_category_name', item.expense_category_name, 'actor_id', item.actor_id, 'actor_display_name', coalesce((select profile.display_name from public.profiles profile where profile.id = item.actor_id), 'Sistema'), 'created_at', item.created_at) order by item.created_at desc, item.movement_id desc) from public.cash_m10_effective_movements(day.id) item where not item.voided), '[]'::jsonb),
    coalesce((select jsonb_agg(jsonb_build_object('id', event.id, 'movement_id', event.movement_id, 'event_type', event.event_type, 'previous_state', event.previous_state, 'new_state', event.new_state, 'reason', event.reason, 'actor_id', event.actor_id, 'actor_display_name', coalesce((select profile.display_name from public.profiles profile where profile.id = event.actor_id), 'Sistema'), 'created_at', event.created_at) order by event.created_at desc, event.id desc) from public.cash_movement_events event where event.cash_day_id = day.id), '[]'::jsonb),
    coalesce((select jsonb_agg(jsonb_build_object('id', event.id, 'sequence_no', event.sequence_no, 'event_type', event.event_type, 'closure_kind', event.closure_kind, 'closing_balance', event.closing_balance, 'actor_id', event.actor_id, 'actor_display_name', coalesce((select profile.display_name from public.profiles profile where profile.id = event.actor_id), 'Sistema'), 'created_at', event.created_at, 'reason', event.reason) order by event.sequence_no desc) from public.cash_day_lifecycle_events event where event.cash_day_id = day.id), '[]'::jsonb);
end; $$;

revoke all on function public.get_current_cash_summary(), public.get_cash_day_summary(uuid) from public, anon;
grant execute on function public.get_current_cash_summary(), public.get_cash_day_summary(uuid) to authenticated;
